version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: labs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labs_app
      POSTGRES_USER: labs_user
      POSTGRES_PASSWORD: labs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - labs-network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labs-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: labs_app
      DB_USERNAME: labs_user
      DB_PASSWORD: labs_password
    depends_on:
      - postgres
    networks:
      - labs-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labs-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - labs-network
    command: npm run dev

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: labs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/public
    depends_on:
      - backend
      - frontend
    networks:
      - labs-network

volumes:
  postgres_data:
    driver: local

networks:
  labs-network:
    driver: bridge

