api:
  key: 935156e6f72cb32a49564de16dbdf1f8f6f3bb6fa127f283233ebbaef43b4390
  url: http://10.5.254.70/api/v1/agent
coleta:
  intervalo_segundos: 300
laboratorio:
  id: 1
logging:
  arquivo: agent.log
  level: INFO
  max_size_mb: 10
